In [25]:
#Import Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import pickle

In [26]:
#Load The CSV DataFile
Startup = pd.read_csv('Startups_Dataset_Sample.csv')

In [27]:
#Execute the Saple Datset
Startup

R&D_Spend  Administration  Marketing_Spend       State     Profit
0    183395.74       194312.91        309794.25    New York  161014.22
1    170178.04       119466.88        359255.18     Florida  228226.10
2    198670.64        68196.81         90071.59     Florida  109778.19
3     60524.15        50724.34        378256.66     Florida  203032.57
4     52552.25        70039.87        171105.23  California  212115.84
..         ...             ...              ...         ...        ...
495  119625.85        65214.52        119405.94    New York  214599.66
496  127796.24        66153.82         57857.60    New York  147568.15
497  155610.89       134360.85         42851.94  California   87443.63
498  159175.57       185879.39        289843.86     Florida  144032.94
499   83976.33       122264.08         84277.92  California  132814.50

[500 rows x 5 columns]

In [28]:
#Check the Shape of the DataSet
Startup.shape

(500, 5)

In [29]:
#Check the Unique data
Startup.State.unique()

array(['New York', 'Florida', 'California'], dtype=object)

In [30]:
#Check the Isnull of the DataSet
Startup.isnull().sum()

R&D_Spend          0
Administration     0
Marketing_Spend    0
State              0
Profit             0
dtype: int64

In [31]:
#Convert String Data Into Int Data types
#Use the Label encoder
labelEncoder = LabelEncoder()
Startup['State'] = labelEncoder.fit_transform(Startup['State'])

In [32]:
#Check the Converted Data
Startup.head()

R&D_Spend  Administration  Marketing_Spend  State     Profit
0  183395.74       194312.91        309794.25      2  161014.22
1  170178.04       119466.88        359255.18      1  228226.10
2  198670.64        68196.81         90071.59      1  109778.19
3   60524.15        50724.34        378256.66      1  203032.57
4   52552.25        70039.87        171105.23      0  212115.84

In [33]:
#Execute the data to array from dataset (Two Demention)
x = np.array(Startup.drop(columns=['Profit']))
y = np.array(Startup['Profit'])

In [34]:
#Get the data to train the model
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [35]:
#Execute the Data for Train
x_train

array([[1.5292162e+05, 9.9737330e+04, 3.0903471e+05, 1.0000000e+00],
       [7.7807090e+04, 1.2130823e+05, 2.7945990e+04, 1.0000000e+00],
       [1.2159925e+05, 5.4902150e+04, 2.9703497e+05, 2.0000000e+00],
       ...,
       [1.1831912e+05, 1.2324929e+05, 3.0775108e+05, 1.0000000e+00],
       [1.7028606e+05, 7.8033440e+04, 2.7612099e+05, 1.0000000e+00],
       [1.3271746e+05, 1.4684091e+05, 2.1959085e+05, 0.0000000e+00]])

In [36]:
#Execute the Data for Test
x_test

array([[8.6085600e+04, 8.6852190e+04, 3.8264455e+05, 2.0000000e+00],
       [6.8133960e+04, 6.8503980e+04, 2.6933263e+05, 0.0000000e+00],
       [1.3822713e+05, 1.0460094e+05, 2.3755152e+05, 0.0000000e+00],
       [1.8497772e+05, 1.1784956e+05, 8.7920750e+04, 2.0000000e+00],
       [1.2611169e+05, 1.4999693e+05, 2.0288753e+05, 0.0000000e+00],
       [1.8802428e+05, 1.2386483e+05, 6.0126170e+04, 2.0000000e+00],
       [1.2073593e+05, 1.3176944e+05, 3.8055096e+05, 1.0000000e+00],
       [1.4280755e+05, 1.5860091e+05, 2.5951392e+05, 2.0000000e+00],
       [1.2436892e+05, 1.5486276e+05, 2.7920040e+05, 2.0000000e+00],
       [1.1998240e+05, 1.4715953e+05, 3.9224068e+05, 0.0000000e+00],
       [1.0199119e+05, 1.8540384e+05, 2.8674110e+04, 0.0000000e+00],
       [1.5685922e+05, 7.5958510e+04, 3.8178849e+05, 2.0000000e+00],
       [1.8083827e+05, 1.2420108e+05, 6.4219090e+04, 2.0000000e+00],
       [1.9971367e+05, 1.8758932e+05, 5.6789250e+04, 0.0000000e+00],
       [1.2642018e+05, 1.7696694e+

In [37]:
#Execute the Data for Train
y_train

array([147749.5 , 132503.84,  73490.99,  50038.  , 143913.58, 191837.61,
       183417.5 , 152093.6 , 128617.95, 104354.96, 165302.86, 209238.65,
        76051.9 , 136585.55, 212790.07, 135767.03,  57930.91, 212629.61,
       135538.18, 212450.63, 238144.98,  95759.7 ,  95505.87, 180024.37,
       193586.95, 238208.05, 187822.53, 218147.51,  70730.94, 137410.72,
       174234.77,  62569.93, 231886.09,  71626.5 , 162456.34, 201746.51,
        85056.71, 135018.7 , 128678.23, 207781.78, 243936.19, 218495.38,
        71176.2 , 248542.61, 138688.7 , 166815.58, 154221.09,  52557.01,
       175499.71,  70212.37, 205058.81, 173905.46, 208599.59, 101120.94,
        71104.76,  60371.42, 203032.57, 181417.26, 116234.7 , 163185.85,
        76050.53, 214526.95,  84403.12,  72060.47, 203303.45,  95888.34,
       122153.92, 175583.22, 199978.29,  54074.99,  52887.66,  87886.67,
       102426.48, 161149.46, 127781.23,  89512.96, 122132.91, 245124.43,
       216220.39,  62380.21, 135205.16, 142824.32, 

In [38]:
#Execute the Data for Test
y_test

array([106549.98,  79890.61,  80760.36, 131506.72, 223380.25,  86347.59,
       145215.98,  93938.46,  89250.46,  67922.81, 218346.52, 247653.61,
        54546.48,  52656.96, 240510.22,  66633.66, 214599.66, 124163.57,
        96943.92, 186003.22, 122379.26, 188312.26, 175128.14, 218938.82,
       191251.42, 227535.09,  87443.63,  63084.88, 151750.87,  60877.05,
       184313.14,  93028.73,  57670.38, 124188.14, 109778.19, 136825.27,
        91447.09, 103022.16, 249435.93, 216056.26,  56892.37, 107693.1 ,
       206348.71, 152524.97, 142491.72, 103846.73, 161014.22,  68372.15,
       171291.24, 119495.27,  54452.56, 242533.51,  86028.78,  58508.55,
        66213.59, 127229.56, 186608.61, 136821.68, 102547.98, 215608.14,
       115367.75, 130463.52, 100465.58, 115935.34, 202634.91, 175411.92,
       200050.12,  95823.1 , 170737.83, 221606.43,  90654.86,  72535.4 ,
       107865.78, 225632.86,  87754.1 , 104921.8 ,  97269.47, 198271.38,
       214159.19,  87301.75, 191659.63, 153250.83, 

In [39]:
#Train the Model
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [40]:
#Create a sample prediction  get method
predict = model.predict([[168552,145823,412852,1]])
predict[0]

np.float64(148023.25348080992)

In [41]:
# Check the Model Accuracy
Accuracy = model.score(x_test,y_test)
Accuracy

-0.06953246941352265

In [42]:
#Check the coefficient the Dataset
model.coef_

array([ 8.50186664e-02,  9.30904529e-02, -2.89027127e-02,  4.12939863e+02])

In [43]:
#Check coefficient from dataset
pd.DataFrame(model.coef_,["R&D_Spend","Administration","Marketing_Spend","State	Profit"],columns=['coef'])

coef
R&D_Spend          0.085019
Administration     0.093090
Marketing_Spend   -0.028903
State\tProfit    412.939863

In [46]:
#Save the Model
with open("model.pickel","wb") as file:
    pickle.dump(model,file)